import React,{useEffect,useRef,useState} from 'react';
import {Alert,ScrollView,Text,View} from 'react-native';
import {LinearGradient} from 'expo-linear-gradient';
import {collection,doc,getDocs,onSnapshot,query,setDoc,where} from 'firebase/firestore';
import {db,DATA_PATH} from './firebase';
import {runTransaction} from './booking-transactions';
import useReservations from './useReservations';
import useScreenBack from './useScreenBack';
import {Action,LoadState,openLink,ui} from './native-ui';
import {mapsUrl,money,whatsappUrl} from './workspace-data.mjs';
import {resourcesFromConfig} from './admin-settings.mjs';
import {assignSanta,changeChristmasDelivery,christmasSummary,deleteChristmasReservation,delivered,santaConflict,santaRouteUrl} from './christmas-operations.mjs';
import {firestoreErrorMessage} from './firebase-errors.mjs';
export default function ChristmasOperationsScreen({onClose,onOpen,onRequests,settings}) {
 const data=useReservations({start:'2026-12-24',end:'2026-12-25'});
 const [day,setDay]=useState('all'),[expanded,setExpanded]=useState(null),[capacity,setCapacity]=useState(1),[configReady,setConfigReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const lock=useRef(false);
 useScreenBack(onClose,busy);
 useEffect(()=>onSnapshot(doc(db,...DATA_PATH,'config_web','global'),{includeMetadataChanges:true},snap=>{setConfigReady(!snap.metadata?.fromCache&&!snap.metadata?.hasPendingWrites);setCapacity(resourcesFromConfig(snap.data()||{}).capacidadSanta);},()=>{setConfigReady(false);setError('No pudimos actualizar la capacidad Santa.');}),[]);
 const summary=christmasSummary(data.events,capacity,day),blocked=busy||data.loading||!!data.error||data.cached||!configReady;
 const ref=id=>doc(db,...DATA_PATH,'eventos',id);
 async function perform(event,kind,santa,allowConflict=false) {
  if(lock.current)return;lock.current=true;setBusy(true);setError('');setSuccess('');
  try {
   const args={runTransaction,db,ref:ref(event.id),event,now:new Date().toISOString()};
   if(kind==='assign'){
    const rows=await getDocs(query(collection(db,...DATA_PATH,'eventos'),where('fecha','==',event.fecha)));
    await assignSanta({...args,santa,allowConflict,configRef:doc(db,...DATA_PATH,'config_web','global'),otherRefs:rows.docs.filter(row=>row.id!==event.id).map(row=>ref(row.id))});
    setSuccess(`Reserva reasignada a ${santa}.`);
   } else if(kind==='delete') {await deleteChristmasReservation(args);setExpanded(null);setSuccess('Reserva eliminada y cupo liberado en la web.');}
   else {await changeChristmasDelivery({...args,complete:kind==='complete'});setSuccess(kind==='complete'?'Entrega realizada. La ruta deja de incluirla.':'Entrega devuelta a pendiente.');}
   setDoc(doc(db,...DATA_PATH,'configuracion','syncBus'),{entityType:'evento',entityId:event.id,action:kind==='delete'?'delete':'update',deviceId:'diverty-native',changedAt:new Date().toISOString(),nonce:`christmas-${Date.now()}`}).catch(()=>{});
  }catch(e){
   if(e.message==='SANTA_CONFLICT'&&!allowConflict){Alert.alert('Revisar tiempo',`${santa} ya tiene una ruta que puede chocar con este horario. ¿Deseas asignarlo de todas formas?`,[{text:'Cancelar',style:'cancel'},{text:'Asignar de todas formas',onPress:()=>perform(event,'assign',santa,true)}]);}
   else setError(({EVENT_CHANGED:'La reserva cambió en otro dispositivo. Revisa los datos actualizados antes de repetir.',EVENT_NOT_FOUND:'La reserva ya no está disponible.',NOT_ACTIVE_CHRISTMAS:'Esta reserva ya no es una entrega navideña activa.',SANTA_UNAVAILABLE:'Ese Santa ya no está disponible. Revisa la capacidad actual.'})[e.message]||firestoreErrorMessage(e));
  }finally{lock.current=false;setBusy(false);}
 }
 async function hide(){if(lock.current)return;lock.current=true;setBusy(true);try{await settings.savePreferences({...settings.preferences,christmasModuleVisible:false});onClose();}catch{setError('No pudimos guardar la visibilidad del módulo. Reintenta.');}finally{lock.current=false;setBusy(false);}}
 return <ScrollView style={ui.page} contentContainerStyle={ui.scroll}><Action title="Agenda" secondary disabled={busy} onPress={onClose}/><LinearGradient colors={['#7F1D1D','#C62828','#EA580C']} style={{padding:22,borderRadius:24,gap:12}}><Text style={{color:'white',fontWeight:'800',fontSize:28}}>Operación Navidad</Text><Text style={{color:'white'}}>24 y 25 de diciembre · Entregas, siguiente parada y rutas por Santa</Text><Text style={{color:'white'}}>{summary.pending} pendientes · {summary.completed} realizadas · {summary.requests.length} por revisar · {capacity} Santas</Text></LinearGradient><LoadState {...data}/>{!configReady?<Text style={ui.muted}>Esperando la capacidad confirmada por Firebase…</Text>:null}<View style={ui.row}>{[['all','24 + 25'],['24','24 Dic'],['25','25 Dic']].map(([value,title])=><View key={value} style={{flex:1}}><Action title={title} secondary={day!==value} disabled={busy} onPress={()=>{setDay(value);setExpanded(null);}}/></View>)}</View><Text style={ui.body}>Marca cada visita como Entrega realizada. La ruta deja de incluirla y la siguiente parada queda resaltada automáticamente.</Text><Action title={`Revisar solicitudes (${summary.requests.length})`} secondary disabled={busy} onPress={onRequests}/>{error?<Text accessibilityRole="alert" style={ui.error}>{error}</Text>:null}{success?<Text accessibilityRole="alert" style={ui.success}>{success}</Text>:null}{!data.loading&&!data.error&&!summary.stops.length?<Text style={ui.body}>Aún no hay entregas confirmadas. Las reservas aceptadas del 24 y 25 aparecerán aquí.</Text>:null}
 {!data.loading&&!data.error?summary.groups.map(group=><View key={group.name} style={ui.card}><Text style={ui.title}>{group.name}</Text><Text style={ui.muted}>{group.pending} pendientes · {group.stops.length-group.pending} realizadas</Text>{group.name!=='Sin asignar'&&group.pending>0?<Action title={`Ruta pendiente de ${group.name}`} secondary disabled={busy||!santaRouteUrl(group.stops)} onPress={()=>openLink(santaRouteUrl(group.stops))}/>:null}{group.stops.map((event,index)=><View key={event.id} style={[ui.card,{borderColor:delivered(event)?'#a7f3d0':group.next?.id===event.id?'#fcd34d':'#e7e4f0'}]}><Text style={ui.muted}>Parada {index+1} · {delivered(event)?'✓ Entregada':group.next?.id===event.id?'Siguiente':'Pendiente'}{santaConflict(event,group.stops)?' · Revisar tiempo':''}</Text><Action title={`${event.hora} · ${event.cliente}`} secondary disabled={busy} onPress={()=>setExpanded(expanded===event.id?null:event.id)}/>{expanded===event.id?<><Text style={ui.body}>{event.fecha} · {event.ninos||'No indicado'} niños</Text>{Number(String(event.ninos||'').match(/\d+/)?.[0]||0)>2?<Text style={ui.error}>Navidad admite máximo 2 niños por reserva. Revisa esta cantidad.</Text>:null}<Text style={ui.body}>Total: {money(event.total)} · Saldo: {money(Math.max(0,Number(event.total||0)-Number(event.abono||0)))}</Text><Text style={ui.body}>{event.servicio}</Text><Text style={ui.body}>{event.descripcionEvento}</Text><Text style={ui.body}>{event.direccion||'Dirección no indicada'}</Text><Text style={ui.body}>{event.referenciaLugar}</Text><Text style={ui.muted}>{event.comentarios}</Text><Text style={ui.title}>Santa asignado</Text>{summary.enabled.map(name=><Action key={name} title={`Asignar ${name}`} secondary={event.santaAsignado!==name} disabled={blocked} onPress={()=>perform(event,'assign',name)}/>)}<Action title="WhatsApp" secondary disabled={busy||!whatsappUrl(event.telefono)} onPress={()=>openLink(whatsappUrl(event.telefono))}/><Action title="GPS / Waze" secondary disabled={busy||!mapsUrl(event)} onPress={()=>openLink(mapsUrl(event))}/><Action title={delivered(event)?'Volver a pendiente':'Marcar entrega realizada'} disabled={blocked} onPress={()=>perform(event,delivered(event)?'reopen':'complete')}/><Action title="Ver reserva y acciones" secondary disabled={busy} onPress={()=>onOpen(event)}/><Action title="Eliminar reserva y liberar cupo" danger disabled={blocked} onPress={()=>Alert.alert('Eliminar reserva',`¿Eliminar la reserva navideña de ${event.cliente}? El horario se liberará en la web.`,[{text:'Cancelar',style:'cancel'},{text:'Eliminar',style:'destructive',onPress:()=>perform(event,'delete')}])}/></>:null}</View>)}{!group.stops.length?<Text style={ui.muted}>Sin entregas asignadas.</Text>:null}</View>):null}
 <View style={ui.card}><Text style={ui.title}>Cuando termine la temporada</Text><Text style={ui.body}>Puedes quitar Operación Navidad de Inicio y Agenda sin borrar las reservas ni el historial.</Text><Action title="Finalizar temporada y ocultar módulo" secondary disabled={busy||!settings.ready} onPress={()=>Alert.alert('Finalizar temporada','Se ocultará el módulo en este teléfono. Puedes volver a mostrarlo desde Ajustes → Herramientas del sistema.',[{text:'Cancelar',style:'cancel'},{text:'Ocultar',onPress:hide}])}/></View></ScrollView>;
}
