import {Calendar,DollarSign,Users,TrendingUp,FileText,Zap,RefreshCw,Plus,ChevronRight} from 'lucide-react-native';
import {WEB_THEME as T,WEB_FONTS as F} from './web-theme.mjs';
import {getResourceAvailability} from './booking-transactions';
import {resourcesFromConfig} from './admin-settings.mjs';
import React,{useEffect,useState} from 'react';
import {doc,onSnapshot} from 'firebase/firestore';
import {db,DATA_PATH} from './firebase';
import {Pressable,ScrollView,Text,View} from 'react-native';
import {LinearGradient} from 'expo-linear-gradient';
import {Action,LoadState,ui} from './native-ui';
import {homeSummary} from './admin-settings.mjs';
import {clientsFromEvents,money} from './workspace-data.mjs';
import ReservationCard from './ReservationCard';
export default function HomeScreen({data,today,settings,onNew,onOpen,onAgenda,onRequests,onChristmas}){
 const [hidden,setHidden]=useState(null),[capacity,setCapacity]=useState(null);
 useEffect(()=>onSnapshot(doc(db,...DATA_PATH,'config_web','global'),{includeMetadataChanges:true},snapshot=>setCapacity(snapshot.metadata?.fromCache?null:resourcesFromConfig(snapshot.data()||{})),()=>setCapacity(null)),[]);
 useEffect(()=>onSnapshot(doc(db,...DATA_PATH,'configuracion','clientesOcultos'),snapshot=>setHidden(Array.isArray(snapshot.data()?.clients)?snapshot.data().clients:[]),()=>setHidden(null)),[]);
 const summary=homeSummary(data.events,today,settings.preferences.metaMensual);
 const operations=summary.today.filter(e=>!e.esNavidad&&!/entregas de nochebuena/i.test(e.servicio||'')),pending=operations.filter(e=>e.estado!=='Completado'),next=pending.find(e=>['En el evento','En camino','Preparando'].includes(e.estado))||pending[0],resources=next&&capacity?getResourceAvailability(next,data.events,capacity):null;
 return <ScrollView style={ui.page} contentContainerStyle={ui.scroll}>
  <LinearGradient colors={T.hero} start={{x:0,y:0}} end={{x:1,y:1}} style={{padding:22,borderRadius:30,gap:10,marginTop:8,borderWidth:1,borderColor:'#FFFFFF18',overflow:'hidden'}}><View pointerEvents="none" style={{position:'absolute',right:-70,bottom:-90,width:230,height:230,borderRadius:140,backgroundColor:'#FF3EA518'}}/><Text style={{color:'#CBD5E1',fontFamily:F.bold,fontSize:13}}>Buenas tardes ☀️</Text><Text style={{color:'#fff',fontFamily:F.black,fontSize:34,letterSpacing:-1.5}}>Hola Diverty 👋</Text><Text style={{color:'#CBD5E1',fontFamily:F.semibold,fontSize:13,lineHeight:20}}>Gestiona tus reservas, contratos y finanzas al instante.</Text><Action title="Nueva Reserva" icon={Plus} onPress={()=>onNew({})}/></LinearGradient>
  {settings.preferences.christmasModuleVisible?<Pressable accessibilityRole="button" accessibilityLabel="Operación Navidad" onPress={onChristmas}><LinearGradient colors={['#D91F2D','#EF3F2F','#F59E0B']} start={{x:0,y:0}} end={{x:1,y:0}} style={{borderRadius:22,padding:16,flexDirection:'row',alignItems:'center',gap:12}}><Text style={{fontSize:28}}>🎅</Text><View style={{flex:1}}><Text style={{color:'#FFFFFFBB',fontFamily:F.black,fontSize:9,letterSpacing:1}}>TEMPORADA NAVIDEÑA</Text><Text style={{color:'#fff',fontFamily:F.black,fontSize:17}}>Operación Navidad</Text><Text style={{color:'#FFFFFFCC',fontFamily:F.bold,fontSize:10}}>24–25 dic · Santas · rutas · reservas</Text></View><ChevronRight size={21} color="#fff"/></LinearGradient></Pressable>:null}<LoadState {...data}/>
  {!data.loading&&!data.error?<>
   <View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}>{[['Eventos Hoy',summary.today.length,Calendar,T.purple],['Ingresos Mes',money(summary.finance.received),DollarSign,T.green],['Clientes Activos',hidden?clientsFromEvents(data.events,hidden).length:'—',Users,'#3B82F6'],['Por cobrar este mes',money(summary.finance.balance),TrendingUp,T.pink]].map(([title,value,Icon,color])=><View key={title} style={[ui.card,{width:'48%',flexGrow:1,minHeight:130,borderRadius:22,padding:14,gap:6}]}><View style={{backgroundColor:color+'18',width:40,height:40,borderRadius:14,alignItems:'center',justifyContent:'center'}}><Icon size={19} strokeWidth={2.4} color={color}/></View><Text style={{fontFamily:F.black,fontSize:9,letterSpacing:1,color:'#94A3B8',textTransform:'uppercase',marginTop:5}}>{title}</Text><Text adjustsFontSizeToFit numberOfLines={1} style={{fontFamily:F.black,fontSize:30,letterSpacing:-1,color:title==='Ingresos Mes'?T.green:T.ink}}>{value}</Text></View>)}</View>
   <View style={{backgroundColor:T.navy,borderRadius:22,padding:12,flexDirection:'row',gap:8,alignItems:'center'}}><View style={{flex:1}}><Action title="Cotizar" icon={FileText} secondary onPress={()=>onNew({estado:'Cotización'})}/></View><View style={{flex:1}}><Action title="Operativo" icon={Zap} onPress={onAgenda}/></View><Pressable accessibilityRole="button" accessibilityLabel="Refrescar" onPress={data.reload} style={{padding:8}}><RefreshCw size={21} color="#F0ABFC"/></Pressable></View>
   <Action title={`Solicitudes web (${summary.requests.length})`} secondary onPress={onRequests}/>
   <View style={ui.card}><Text style={ui.title}>Centro de operaciones</Text><Text style={ui.body}>Hoy: {summary.today.length} · Mañana: {summary.tomorrow.length} · Semana: {summary.week.length}</Text><Text style={ui.muted}>Cotizaciones: {summary.quotes.length} · Solicitudes web: {summary.requests.length}</Text></View>
   <View style={ui.card}><Text style={ui.title}>Operación de hoy</Text><Text style={ui.body}>{operations.length} eventos · {operations.length-pending.length} realizados · {pending.length} pendientes</Text>{next?<><Text style={ui.title}>{next.cliente} · {next.hora}</Text><Text style={ui.body}>{next.estado}</Text>{resources?<Text style={resources.feasible?ui.body:ui.error}>Animadores libres: {resources.available.animadores} / {resources.capacity.animadores} · Payasos libres: {resources.available.payasos} / {resources.capacity.payasos}{resources.feasible?'':' · Revisa la disponibilidad de personal'}</Text>:<Text style={ui.muted}>Esperando capacidad del servidor…</Text>}<Action title="Abrir siguiente evento" onPress={()=>onOpen(next)}/></>:<Text style={ui.body}>Sin eventos pendientes hoy.</Text>}</View><View style={ui.card}><Text style={ui.title}>Meta mensual</Text><Text style={ui.body}>{money(summary.finance.total)} / {money(summary.goal)}</Text><View style={{height:8,backgroundColor:'#ece9f5',borderRadius:8}}><View style={{height:8,width:`${summary.progress}%`,backgroundColor:'#7657FF',borderRadius:8}}/></View></View>
   <Text style={ui.heading}>Próximos eventos</Text>{summary.upcoming.slice(0,5).map(event=><ReservationCard key={event.id} event={event} onOpen={onOpen}/>)}{!summary.upcoming.length?<Text style={ui.muted}>No hay eventos próximos.</Text>:null}
  </>:null}
 </ScrollView>;
}
