import React from 'react';
import {ActivityIndicator,Alert,Linking,Pressable,StyleSheet,Text,View} from 'react-native';
import {monthLabel} from './workspace-data.mjs';
import {LinearGradient} from 'expo-linear-gradient';
import {ChevronRight} from 'lucide-react-native';
import {WEB_THEME as T,WEB_FONTS as F} from './web-theme.mjs';

export function Action({title,onPress,disabled=false,secondary=false,danger=false,icon:Icon}){
 const content=<><View style={{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,flex:1}}>{Icon?<Icon size={19} color={secondary?T.purple:'#fff'}/>:null}<Text style={[ui.buttonText,secondary&&ui.secondaryText]}>{title}</Text></View>{secondary?<ChevronRight size={16} color={T.purple}/>:null}</>;
 return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[ui.button,secondary&&ui.secondary,danger&&ui.danger,disabled&&{opacity:.45}]}>{secondary||danger?<View style={ui.buttonInner}>{content}</View>:<LinearGradient colors={T.primary} start={{x:0,y:0}} end={{x:1,y:1}} style={ui.buttonInner}>{content}</LinearGradient>}</Pressable>;
}
export function LoadState({loading,error,cached,reload}){
 return <>{loading?<ActivityIndicator size="large" color="#7657FF"/>:null}{error?<View style={ui.card}><Text accessibilityRole="alert" style={ui.error}>{error}</Text><Action title="Reintentar" onPress={reload}/></View>:null}{cached&&!loading&&!error?<Text style={ui.muted}>Datos guardados en este dispositivo. Esperando conexión para actualizar.</Text>:null}</>;
}
export function MonthSelector({month,onMove,disabled=false}){
 return <View style={ui.month}><Pressable accessibilityRole="button" accessibilityLabel="Mes anterior" disabled={disabled} onPress={()=>onMove(-1)} style={ui.arrow}><Text style={ui.arrowText}>‹</Text></Pressable><Text style={ui.monthText}>{monthLabel(month)}</Text><Pressable accessibilityRole="button" accessibilityLabel="Mes siguiente" disabled={disabled} onPress={()=>onMove(1)} style={ui.arrow}><Text style={ui.arrowText}>›</Text></Pressable></View>;
}
export async function openLink(url){
 if(!url)return Alert.alert('Contacto no disponible','Revisa el teléfono o la dirección guardada en la reserva.');
 try{await Linking.openURL(url);}catch{Alert.alert('No se pudo abrir','Comprueba que tienes una aplicación para abrir este enlace.');}
}
export const ui=StyleSheet.create({page:{flex:1,paddingHorizontal:14,backgroundColor:T.background},scroll:{paddingTop:8,paddingBottom:28,gap:14},heading:{fontSize:28,fontFamily:F.black,color:T.ink,letterSpacing:-.8,marginVertical:12},title:{fontSize:18,fontFamily:F.black,color:T.ink,letterSpacing:-.3},body:{fontSize:14,fontFamily:F.semibold,color:'#475569',lineHeight:21},muted:{fontSize:12,fontFamily:F.semibold,color:T.muted,lineHeight:19},card:{backgroundColor:'#fff',borderRadius:26,padding:18,gap:10,borderWidth:1,borderColor:T.border,shadowColor:'#475569',shadowOffset:{width:0,height:6},shadowOpacity:.07,shadowRadius:15,elevation:2},input:{backgroundColor:'#fff',borderWidth:1,borderColor:T.border,borderRadius:16,padding:14,fontSize:16,fontFamily:F.regular,color:T.ink},button:{borderRadius:16,marginTop:4,overflow:'hidden',minHeight:48},buttonInner:{minHeight:48,paddingVertical:14,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:8},buttonText:{color:'#fff',textAlign:'center',fontFamily:F.black,fontSize:13,letterSpacing:.25,flexShrink:1},secondary:{backgroundColor:'#fff',borderWidth:1,borderColor:T.border},secondaryText:{color:T.purple},danger:{backgroundColor:'#E11D48'},error:{fontFamily:F.semibold,color:'#E11D48',lineHeight:21},success:{fontFamily:F.semibold,color:T.green,lineHeight:21},row:{flexDirection:'row',gap:10,alignItems:'center'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:'#fff',borderWidth:1,borderColor:T.border,borderRadius:14,paddingHorizontal:12,paddingVertical:10},activeChip:{backgroundColor:T.purple,borderColor:T.purple},chipText:{color:T.muted,fontSize:11,fontFamily:F.bold},activeText:{color:'#fff'},month:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10,backgroundColor:'#fff',borderRadius:18,padding:6,borderWidth:1,borderColor:T.border},monthText:{fontFamily:F.black,fontSize:18,color:T.ink,textTransform:'capitalize',flex:1,textAlign:'center'},arrow:{paddingHorizontal:16,paddingVertical:8,borderRadius:12,backgroundColor:'#F2EEFF'},arrowText:{fontSize:24,color:T.purple,fontFamily:F.bold}});
