import React,{useEffect,useRef,useState} from 'react';
import {Alert,ScrollView,Text,TextInput,View} from 'react-native';
import {doc,onSnapshot} from 'firebase/firestore';
import {db,DATA_PATH} from './firebase';
import {Action,ui} from './native-ui';
import {money,webRequest} from './workspace-data.mjs';
import {inferResourceRequirements} from './booking-transactions';
import {updateRequest,confirmRequest,rejectRequest} from './request-actions';
import {christmasRequest,requestMessages} from './request-data.mjs';
import {transportPending} from './domain/web-request-review.mjs';
import useScreenBack from './useScreenBack';
export default function RequestReviewScreen({event,onClose}){
 const [opened,setOpened]=useState(event),[current,setCurrent]=useState(event),[ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reference,setReference]=useState(event.referenciaLugar||''),[transport,setTransport]=useState(String(event.transporte||0)),[resources,setResources]=useState(inferResourceRequirements(event)),[santa,setSanta]=useState('Santa 1'),[capacity,setCapacity]=useState(1),lock=useRef(false);
 const dirty=reference!==(opened.referenciaLugar||'')||transport!==String(opened.transporte||0)||Object.keys(resources).some(key=>String(resources[key])!==String(inferResourceRequirements(opened)[key]));
 const close=()=>dirty?Alert.alert('Cambios sin guardar','¿Descartar los cambios de la solicitud?',[{text:'Continuar editando',style:'cancel'},{text:'Descartar',style:'destructive',onPress:onClose}]):onClose();useScreenBack(close,busy);
 useEffect(()=>onSnapshot(doc(db,...DATA_PATH,'eventos',event.id),{includeMetadataChanges:true},snap=>{setReady(snap.exists()&&!snap.metadata.fromCache&&!snap.metadata.hasPendingWrites);setCurrent(snap.exists()?{...snap.data(),id:event.id}:null);},()=>{setReady(false);setError('No se pudo actualizar la solicitud. Cierra y reintenta.');}),[event.id]);
 useEffect(()=>onSnapshot(doc(db,...DATA_PATH,'config_web','global'),snap=>{const n=Number(snap.data()?.capacidadSanta||1);setCapacity(Number.isInteger(n)&&n>=1&&n<=20?n:1);},()=>setError('No se pudo cargar la capacidad Santa.')),[]);
 const stale=current&&Number(current._rev||0)!==Number(opened._rev||0),disabled=busy||!ready||!(current&&webRequest(current))||stale;
 async function perform(kind,value){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{if(kind==='confirm'){await confirmRequest(opened,santa);Alert.alert('Reserva confirmada','La solicitud se aceptó en Diverty.');onClose();}else if(kind==='reject'){await rejectRequest(opened);Alert.alert('Solicitud rechazada','El horario quedó liberado.');onClose();}else{const saved=await updateRequest(opened,kind,value);setOpened(saved);if(kind==='reference')setReference(saved.referenciaLugar||'');if(kind==='transport')setTransport(String(saved.transporte));if(kind==='resources')setResources(saved.resourceRequirements);Alert.alert('Solicitud actualizada','Los cambios se guardaron en Diverty.');}}catch(err){setError(requestMessages[err.message]||err.details?.reason&&err.message||'No se pudo guardar. Revisa la conexión y vuelve a abrir la solicitud antes de reintentar.');}finally{lock.current=false;setBusy(false);}}
 const christmas=christmasRequest(opened);
 return <ScrollView style={ui.page} contentContainerStyle={ui.scroll}><Action title="Volver a solicitudes" secondary disabled={busy} onPress={close}/><Text style={ui.heading}>Solicitud Web</Text><View style={ui.card}><Text style={ui.title}>{current?.cliente||opened.cliente}</Text><Text style={ui.body}>{opened.fecha} · {opened.hora}</Text><Text style={ui.body}>{opened.servicio}</Text><Text style={ui.body}>Total: {money(current?.total)} · Abono: {money(current?.abono)}</Text><Text style={ui.muted}>{opened.direccion||opened.ubicacion}</Text></View>
 {stale?<><Text style={ui.error}>La solicitud cambió. Revisa los datos actualizados antes de continuar.</Text><Action title="Cargar solicitud actualizada" disabled={busy} onPress={()=>{setOpened(current);setReference(current.referenciaLugar||'');setTransport(String(current.transporte||0));setResources(inferResourceRequirements(current));setError('');}}/></>:null}
 {!ready&&current?<Text style={ui.muted}>Esperando datos del servidor…</Text>:null}{(!current||ready&&!(current&&webRequest(current)))?<Text style={ui.muted}>La solicitud ya fue procesada o eliminada.</Text>:null}
 <View style={ui.card}><Text style={ui.title}>Referencia del lugar</Text><TextInput accessibilityLabel="Referencia del lugar" value={reference} editable={!disabled} onChangeText={setReference} style={ui.input}/><Action title="Guardar referencia" disabled={disabled} onPress={()=>perform('reference',reference)}/></View>
 <View style={ui.card}><Text style={ui.title}>{transportPending(opened)?'Transporte por confirmar':'Transporte de la solicitud'}</Text><TextInput accessibilityLabel="Transporte de la solicitud" value={transport} editable={!disabled} onChangeText={setTransport} keyboardType="decimal-pad" style={ui.input}/><Action title="Confirmar transporte" disabled={disabled} onPress={()=>perform('transport',transport)}/></View>
 {christmas?<View style={ui.card}><Text style={ui.title}>Asignar Santa</Text>{Array.from({length:capacity},(_,i)=>`Santa ${i+1}`).map(name=><Action key={name} title={name} secondary={santa!==name} disabled={disabled} onPress={()=>setSanta(name)}/>)}</View>:<View style={ui.card}><Text style={ui.title}>Personal para esta reserva</Text>{[['animadores','Animadores',0,50],['payasos','Payasos',0,50],['durationMinutes','Duración en minutos',30,720]].map(([key,title,min,max])=><View key={key}><Text style={ui.body}>{title} ({min}–{max})</Text><TextInput accessibilityLabel={title} value={String(resources[key])} style={ui.input} editable={!disabled} keyboardType="number-pad" onChangeText={value=>setResources(previous=>({...previous,[key]:value}))}/></View>)}<Action title="Guardar personal" disabled={disabled} onPress={()=>perform('resources',resources)}/><Text style={ui.muted}>Al aceptar se comprueba el personal disponible. Un abono no es obligatorio.</Text></View>}
 {dirty?<Text style={ui.muted}>Guarda los cambios de referencia, transporte o personal antes de aceptar.</Text>:null}
 {error?<Text accessibilityRole="alert" style={ui.error}>{error}</Text>:null}<Action title={busy?'Procesando…':'Aceptar reserva'} disabled={disabled||dirty} onPress={()=>Alert.alert('Aceptar solicitud','¿Confirmar esta reserva con los datos guardados?',[{text:'Volver',style:'cancel'},{text:'Aceptar',onPress:()=>perform('confirm')}])}/><Action title="Rechazar solicitud" danger disabled={disabled} onPress={()=>Alert.alert('Rechazar solicitud','¿Rechazar y liberar su horario?',[{text:'Volver',style:'cancel'},{text:'Rechazar',style:'destructive',onPress:()=>perform('reject')}])}/>
 </ScrollView>;
}
