import React,{useEffect,useState} from 'react';
import {Alert,ScrollView,Text,TextInput,View} from 'react-native';
import {doc,onSnapshot,runTransaction} from 'firebase/firestore';
import {db,DATA_PATH} from './firebase';
import {SETTINGS_MENU,resourcesFromConfig,saveCapacity} from './admin-settings.mjs';
import {Action,ui} from './native-ui';
import {prepareDivertyData} from './system-preparation';
export default function SettingsScreen({settings,onBusyChange,onDirtyChange,onSignOut}){
 const [section,setSection]=useState(null),[company,setCompany]=useState(settings.company),[goal,setGoal]=useState(String(settings.preferences.metaMensual)),[config,setConfig]=useState(null),[form,setForm]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>onSnapshot(doc(db,...DATA_PATH,'config_web','global'),{includeMetadataChanges:true},snapshot=>{if(snapshot.metadata?.fromCache||snapshot.metadata?.hasPendingWrites)return;const value=snapshot.data()||{};setConfig(previous=>previous||value);setForm(previous=>previous||resourcesFromConfig(value));},()=>setError('No se pudo cargar la capacidad. Revisa tu conexión.')),[]);
 useEffect(()=>{onBusyChange(busy||settings.saving);return()=>onBusyChange(false);},[busy,settings.saving,onBusyChange]);
 useEffect(()=>{setCompany(settings.company);},[settings.company]);
 async function save(){setBusy(true);setError('');try{if(section==='resources'){const value=await saveCapacity({runTransaction,db,ref:doc(db,...DATA_PATH,'config_web','global'),syncRef:doc(db,...DATA_PATH,'config_web','web_sync'),form,original:config});setConfig(value);}else if(section==='goal'){if(goal.trim()===''||!Number.isFinite(Number(goal))||Number(goal)<0)throw new Error('Ingresa una meta mensual válida.');await settings.savePreferences({...settings.preferences,metaMensual:Number(goal)});}else await settings.saveCompany(company);Alert.alert('Ajustes guardados','Los cambios se guardaron correctamente.');}catch(err){setError(err.message==='CAPACITY_CHANGED'?'La capacidad cambió en otro dispositivo. Vuelve a abrir Ajustes para cargarla antes de guardar.':err.message||'No se pudieron guardar los cambios.');}finally{setBusy(false);}}
 const dirty=JSON.stringify(company)!==JSON.stringify(settings.company)||goal!==String(settings.preferences.metaMensual)||(section==='resources'&&form&&config&&Object.keys(form).some(key=>String(form[key])!==String(resourcesFromConfig(config)[key])));
 useEffect(()=>{onDirtyChange(!!dirty);return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
 const editing=['business','billing','documents','goal','resources'].includes(section);
 async function prepare(){setBusy(true);setError('');try{await prepareDivertyData();Alert.alert('Preparación completada','Disponibilidad pública y numeración preparadas.');}catch(err){setError(err.message==='ADMIN_REQUIRED'?'Se requiere la cuenta administradora.':'Preparación incompleta. Reintenta con conexión y sin otros equipos editando.');}finally{setBusy(false);}}
 return <ScrollView style={ui.page} contentContainerStyle={ui.scroll}><Text style={ui.heading}>Ajustes</Text>{settings.error||error?<Text accessibilityRole="alert" style={ui.error}>{error||settings.error}</Text>:null}
 {!settings.ready?<Action title="Reintentar ajustes" onPress={settings.reload}/>:!section?SETTINGS_MENU.map(([id,title,description])=><View key={id} style={ui.card}><Action title={title} secondary onPress={()=>setSection(id)}/><Text style={ui.muted}>{description}</Text></View>):<>
 <Action title="Volver a ajustes" secondary disabled={busy||settings.saving} onPress={()=>{const discard=()=>{setSection(null);setCompany(settings.company);setGoal(String(settings.preferences.metaMensual));setForm(config?resourcesFromConfig(config):null);setError('');};if(dirty)Alert.alert('Cambios sin guardar','¿Descartar los cambios de ajustes?',[{text:'Continuar editando',style:'cancel'},{text:'Descartar',style:'destructive',onPress:discard}]);else discard();}}/><Text style={ui.title}>{SETTINGS_MENU.find(item=>item[0]===section)?.[1]}</Text>
 {['business','billing','documents'].includes(section)?<><Text style={ui.muted}>Estos datos se guardan en este teléfono y se utilizan también en los PDF.</Text>{(section==='business'?['nombre','telefono','email','web']:['ruc','nombreTitular','banco','tipoCuenta','numeroCuenta']).map(key=><View key={key}><Text style={ui.body}>{({nombre:'Nombre del negocio',telefono:'Teléfono',email:'Correo',web:'Página web',ruc:'RUC',nombreTitular:'Titular',banco:'Banco',tipoCuenta:'Tipo de cuenta',numeroCuenta:'Número de cuenta'})[key]}</Text><TextInput accessibilityLabel={key} style={ui.input} value={company[key]||''} editable={!busy} onChangeText={value=>setCompany(previous=>({...previous,[key]:value}))}/></View>)}</>:null}
 {section==='goal'?<TextInput accessibilityLabel="Meta mensual" style={ui.input} value={goal} keyboardType="decimal-pad" editable={!busy} onChangeText={setGoal}/>:null}
 {section==='resources'?<><Text style={ui.muted}>Se comparte con el administrador web mediante Firebase oficial.</Text>{form?Object.keys(form).map(key=><View key={key}><Text style={ui.body}>{({animadores:'Animadores',payasos:'Payasos',capacidadSimultanea:'Eventos simultáneos',capacidadSanta:'Capacidad Santa'})[key]}</Text><TextInput accessibilityLabel={key} style={ui.input} value={String(form[key])} keyboardType="number-pad" editable={!busy} onChangeText={value=>setForm(previous=>({...previous,[key]:value}))}/></View>):<Text style={ui.muted}>Esperando configuración del servidor…</Text>}</>:null}
 {editing?<Action title={busy?'Guardando…':'Guardar ajustes'} disabled={busy||settings.saving||(section==='resources'&&!form)} onPress={save}/>:null}
 {section==='security'?<Action title="Cerrar sesión" onPress={()=>{if(dirty)Alert.alert('Cambios sin guardar','Guarda o descarta los ajustes antes de cerrar la sesión.');else onSignOut();}}/>:null}
 {section==='tools'?<><View style={ui.card}><Text style={ui.title}>Preparación de disponibilidad pública y numeración</Text><Text style={ui.muted}>Ejecutar una vez después de actualizar, sin otros equipos editando. Reconstruye disponibilidad y cupos desde las reservas existentes y conserva la numeración oficial.</Text><Action title={busy?'Preparando…':'Preparar actualización'} disabled={busy||settings.saving} onPress={()=>Alert.alert('Preparar actualización','¿Preparar disponibilidad y numeración? Confirma que no hay otros equipos editando.',[{text:'Volver',style:'cancel'},{text:'Preparar',onPress:prepare}])}/></View><Text style={ui.body}>Operación Navidad se muestra en Inicio y Agenda. Esta preferencia se guarda en este teléfono.</Text><Action title={settings.preferences.christmasModuleVisible?'Ocultar Operación Navidad':'Mostrar Operación Navidad'} secondary disabled={busy||settings.saving} onPress={async()=>{setBusy(true);setError('');try{await settings.savePreferences({...settings.preferences,christmasModuleVisible:!settings.preferences.christmasModuleVisible});}catch{setError('No pudimos guardar la visibilidad de Operación Navidad.');}finally{setBusy(false);}}}/></>:null}{['notifications','danger'].includes(section)?<Text style={ui.muted}>Esta función del administrador web todavía está pendiente de migración a la app nativa.</Text>:null}
 </>}</ScrollView>;
}
